project:
  type: website
  output-dir: docs

website:
  title: Self-Guided Learning
  page-navigation: true
  cookie-consent:
    express: true
  reader-mode: true
  google-analytics: 
    tracking-id: "G-DQ7RX0NWYQ"

  navbar:
    background: light
    reader-mode: false
    search: true
    right:
      - text: Home
        file: index.qmd
      - text: Software Installs
        file: software-installs.qmd
      - text: Learning Resources
        file: learning-resources.qmd
      - text: Domain-Specific Series
        file: domain-specific-series.qmd
  
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - section: The Unix Shell
        contents:
          - auto: "0-The-Unix-Shell/*"
      - text: "---"
      - section: Reproducibility
        contents:
          - auto: "1-Reproducibility/*"

format:
  html:
    theme: default
    css: styles.css
    toc: true
    toc-depth: 5
    toc-location: right
    fontsize: 1.0em
    fig-responsive: true
    smooth-scroll: true
    page-layout: full

